### ISSUE TITLE
Compiling fails on FreeBSD when the websocket-rustls feature is enabled

### ISSUE THREAD

**Issue by yonas** [rapiz1/rathole#335]
<!-- Please try the latest release before filing a bug report -->

**Describe the bug**
Following #330 , compiling fails on FreeBSD when the `websocket-rustls` feature is enabled.

**To Reproduce**
1. `cargo build --release --features rustls,websocket-rustls`

**Logs**
```
error[E0658]: use of unstable library feature 'stdsimd'                                                                                                                                                              
  --> /code/rathole/work/rathole-4ac53a5/cargo-crates/curve25519-dalek-4.1.2/src/backend/vector/ifma/field.rs:26:5                                                                               
   |                                                                                                                                                                                                                 
26 |     _mm256_madd52lo_epu64(z.into(), x.into(), y.into()).into()
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information
   = help: add `#![feature(stdsimd)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'stdsimd'
  --> /code/rathole/work/rathole-4ac53a5/cargo-crates/curve25519-dalek-4.1.2/src/backend/vector/ifma/field.rs:25:9
   |
25 |     use core::arch::x86_64::_mm256_madd52lo_epu64;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information
   = help: add `#![feature(stdsimd)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'stdsimd'
  --> /code/rathole/work/rathole-4ac53a5/cargo-crates/curve25519-dalek-4.1.2/src/backend/vector/ifma/field.rs:34:5
   |
34 |     _mm256_madd52hi_epu64(z.into(), x.into(), y.into()).into()
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information
   = help: add `#![feature(stdsimd)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'stdsimd'
  --> /code/rathole/work/rathole-4ac53a5/cargo-crates/curve25519-dalek-4.1.2/src/backend/vector/ifma/field.rs:33:9
   |
33 |     use core::arch::x86_64::_mm256_madd52hi_epu64;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information
   = help: add `#![feature(stdsimd)]` to the crate attributes to enable

error[E0635]: unknown feature `stdarch_x86_avx512`
  --> /code/rathole/work/rathole-4ac53a5/cargo-crates/curve25519-dalek-4.1.2/src/lib.rs:19:13
   |
19 |     feature(stdarch_x86_avx512)
   |             ^^^^^^^^^^^^^^^^^^
```

**Environment:**
 - OS: FreeBSD 14
- `rathole --version` output: 4ac53a5
- CPU architecture: amd64

**Comment by rapiz1** [comment]
it looks pretty like a dependency issue. could you please try the latest rust toolchain and compile after a `cargo update`? cc @sunmy2019

**Comment by yonas** [comment]
> could you please try the latest rust toolchain and compile after a `cargo update`?

@rapiz1 Thanks, I'm getting the same error after running `cargo update`.

**Comment by sunmy2019** [comment]
Enabling `rustls` requiring disabling default features. Can you try
```
cargo build --release  --no-default-features --features websocket-rustls
```
?

**Comment by sunmy2019** [comment]
See similar situations in https://github.com/jdx/mise/issues/1630

**Comment by yonas** [comment]
> Would you mind also sharing your rustc version?

rustc 1.76.0-nightly (37b2813a7 2023-11-24) (built from a source tarball)

> Can you try `cargo build --release  --no-default-features --features websocket-rustls`

I'm getting the same errors.

**Comment by rapiz1** [comment]
> rustc 1.76.0-nightly (37b2813a7 2023-11-24) (built from a source tarball)

I can build using `rustc 1.76.0 (07dca489a 2024-02-04)` without issues. You may want to update to the latest stable or nightly.

It's meant to break nightly as per https://github.com/dalek-cryptography/curve25519-dalek/pull/619#issuecomment-1931198286 I agree the their argument as well: no point of supporting out of date nightly

**Comment by sunmy2019** [comment]
> rustc 1.76.0-nightly (37b2813a7 2023-11-24) (built from a source tarball)

One of our dependencies only supports the latest nightly. Others have filed report here: https://github.com/dalek-cryptography/curve25519-dalek/pull/619

Do not use nightly will be good.

**Comment by yonas** [comment]
Upgrading to nightly on linux fixed the issue.

FreeBSD ports doesn't yet have the latest nightly, so I've resorted to pinning curve25519-dalek to v4.1.1.

> Use something other than nightly will be good.

I agree, it should be optional. For example, I wonder if rathole's build.rs / Cargo.toml could detect if nightly is being used and then switch the version of curve25519-dalek from =v4.1.1 to >=v4.1.2.

**Comment by rapiz1** [comment]
Glad to hear that it worked for you. That is possible but we will not introduce the maintenance burden for an outdated nightly build. Whenever FreeBSD gets to the latest *nightly or stable* of rustc, it will work seamlessly,
